language: python
python:
  - "2.7"

before_script:
  - sh -c "psql -c 'CREATE ROLE djangoapp WITH SUPERUSER LOGIN;' -U postgres; fi"
  - npm install -g npm@latest
  - npm install -g babel-eslint@4.1.6
  - cd webapp/ && npm install && npm install -g gulp && cd ..

script:
  - python manage.py test --settings=rhizome.settings.test
  - cd webapp && gulp build && gulp mocha && cd ..

notifications:
  slack:
    $SLACK_ACCESS_KEY

deploy:
  provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  # bucket: rhizome-dev
  revision_type: github
  application: rhizome_test
  region: us-east-1
  deployment_group: rhizome_test_deploy
  skip_cleanup: true
  on:
    branch: development